# Supported funding platforms
github: [your-github-username]
patreon: palimpsest-license
open_collective: palimpsest-license
ko_fi: your_ko_fi_username
custom: ["https://palimpsestlicense.org/donate"] # Your custom donation link