# .github/FUNDING.yml

open_collective: palimpsest-license
patreon: palimpsest-license
liberapay: palimpsest-license
ko_fi: palimpsest-license
custom:
  - https://monero.address.example   # replace with actual XMR address page
  - https://github.com/hyperpolymath/palimpsest-license
